name: Build FFXIV Zoom Hack

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: '[,17)'
          msbuild-architecture: x64

      - name: Build release application
        run: msbuild /t:rebuild /p:Configuration=Release .\FFXIVZoomHack.sln /p:RestorePackagesConfig=true

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "FFXIVZoomHack.exe"
          path: "FFXIVZoomHack\\bin\\Release\\FFXIVZoomHack.exe"
